### PR TITLE
Changes "new feature request" to "new post"

### PR DESCRIPTION
**Pull request by JimMargolis**

### CODE REVIEW

**Comment by JimMargolis** [comment]
@chips-gpx Seems like the easiest way to [fix this](https://gaiagps.slack.com/archives/DQ8JG4PQS/p1600291365000900) is to change "feature request" to "post."  Looks like Robyn changed this at one point: https://github.com/trailbehind/NG_Help_Center/pull/10 

If it seems better to just have the General Discussion forum say "new post," and the feature request forums say "new feature request," I can look into it, but in my initial scan it seems like this would be complicated.

**Comment by JimMargolis** [comment]
I made this change live on the HC if you want to preview

**Comment by chips-gpx** [comment]
lgtm. I think changing this back to "new post" makes more sense at this point. In order to have some buttons say "New Feature Request" how complicated are we talking?

**Comment by JimMargolis** [comment]
@chips-gpx Sorry, I lost track of this.  I'm not sure how much time it would take.  I imagine it might take me or anyone new to programming about 2-4 hours.  I think you could do something in the code to identify if the URL is in the feature request section, and then use an if statement to change the button text based on that.  This doesn't feel very high priority to me.

**Pull request merged**
